### ISSUE TITLE
Potential in mesh_navigation for staircase climbing

### ISSUE THREAD

**Issue by derektan95** [uos/mesh_navigation#11]
Hi @mklpiening, 
Just wanted to firstly express my gratitude for this new package. It really makes 3D navigation much more accessible to ROS users like me. 

I would like to enquire on the potential for using mesh_navigation on multi-level navigation, for instance, in a building where humans would normally ascend or descend via staircases? Correct me if I am wrong, but it seems to me that there cannot be multiple map layers on the same map (when it comes to mapping an entire multi-level building). In addition, I am not sure if we could send a command pose that has a Z (height) component? 

Looking forward to hearing from you, thanks!

**Comment by spuetz** [comment]
> I would like to enquire on the potential for using mesh_navigation on multi-level navigation, for instance, in a building where humans would normally ascend or descend via staircases? Correct me if I am wrong, but it seems to me that there cannot be multiple map layers on the same map (when it comes to mapping an entire multi-level building).

This is possible if the 3D map (triangle mesh) represents that building! We call this multiple level (multi story building). We use the term multi-layer for multiple cost-layers defined on the mesh surface.

> In addition, I am not sure if we could send a command pose that has a Z (height) component?

This is possible too! With the mesh tools package bundle we provide a goal selection too for picking a goal on the mesh surface which of course also uses the z value if you, for example, pick a goal on the second floor, in your example.

Cheers, Sebastian

**Comment by spuetz** [comment]
Regarding stair cases: If the current stack of levels and the current planners could not handle this planning problem well enough, you could develop new layers plugins and / or a new planner plugin.

**Comment by derektan95** [comment]
Thank you @spuetz , I am excited to give this a shot! Can't wait for the dynamic obstacle avoidance feature.
