### ISSUE TITLE
Conflict with libpcl-dev and ros-noetic-desktop-full

### ISSUE THREAD

**Issue by tpet** [uos/mesh_navigation#12]
The ros-noetic-mesh-navigation package seems to be conflicting with libpcl-dev and therefore ros-noetic-desktop-full. It needs libvtk6-dev and libvtk6-qt-dev, which are in conflict with libvtk7-dev and libvtk7-qt-dev needed by libpcl-dev.

Can ros-noetic-mesh-navigation be migrated to libvtk7-dev to resolve the conflict?

**Comment by spuetz** [comment]
Thanks for your input! It is a problem with lvr2 and rosdep. We are already on it! See https://github.com/ros/rosdistro/pull/27768 This will probably merged soon, as all three reviewers already approved the PR.

**Comment by tpet** [comment]
Glad to hear that, thanks!

**Comment by spuetz** [comment]
Solved.
