### ISSUE TITLE
Online mesh mapping?

### ISSUE THREAD

**Issue by sukhrajklair** [uos/mesh_navigation#15]
Hi 

Is it possible to use this package online e.x. in conjunction with SLAM or dynamically construct local costmap straight from the lidar pointlcouds?

**Comment by derektan95** [comment]
Hi @spuetz, 

I am also curious about this question. There have been rather effective SLAM algorithms in building 3d maps online as the robot is navigating in unknown environments. For instance, [RTABMap](http://wiki.ros.org/rtabmap_ros) can output 3d pointcloud maps on the fly. 

I wonder if it's possible to convert the 3d pointcloud map to your mesh map in realtime? How computational intensive is such an operation? Will it affect the smoothness of the path planner should the mesh map be reconstructed on the fly?

Regards,
Derek

**Comment by spuetz** [comment]
Hi @sukhrajklair  and @derektan95 Online mesh mapping is planned in future work. Maybe I can answer you specific questions then.
