### ISSUE TITLE
Running Pluto Simulation with mesh_navigation

### ISSUE THREAD

**Issue by zenified** [uos/mesh_navigation#16]
Hi,
I have installed both mesh_navigation and the Pluto simulation package. However, I am having issue replicating the activities from the demo videos. 

What I did was: 
1. Starting Gazebo via  `roslaunch pluto_gazebo pluto_botanical_garden.launch`
2. Starting mesh_navigation via `roslaunch pluto_navigation botanical_garden_osnabrueck.launch`
3. Sending the goal via `roslaunch pluto_navigation experiment.launch experiment:=botanical_garden_3_dijkstra`

I seems to be able to get the planner working, with the planned path visualized, but the src pose does not correspond to the position of the robot, and no cmd vel was issued from the mbf.   In addition, the position of the robot in RVIZ also don't seem to align with Gazebo.
<img src=https://user-images.githubusercontent.com/5706546/128991067-4a3b9c9c-6543-4e9d-bd92-854492792f5e.png width=60% height=60%>

Am I missing out some modules? 

Lastly, would I be wrong to understand that this package only deals with path planning, and does not have any mesh based localization functionality

**Comment by spuetz** [comment]
Hi @zenified 
With the experiment launch file you only call the planner to compute a path for a pre-defined start and goal pair which is defined in the specified experiment file. In your case this file is called `botanical_garden_3_dijkstra.bagy` 

To plan and execute a path with respect to the current robot position, you does not need the `experiment.launch`

Usually, by starting the launch files within `pluto_navigation` a SMACH will be started. This SMACH subscribes on a goal topic. This can be triggered from with in RViz. Try to use the `Mesh Goal' tool. You have to add this tool first in / to the top panel of RViz using the `+` symbol next to the `2D Nav Goal` and the `Publish Point`.

You are right this package "only" deals with path planning. Localization on meshes is another complex research topic.

**Comment by zenified** [comment]
Hi @spuetz 
Thank you for the quick response and kind assistance. 
Indeed localization on meshes is a challenging topic, I look forward to the teams's'future works with mesh-based maps.

**Comment by JACKLiuDay** [comment]
Hi, I tried the mesh goal with rviz. But when I click mesh goal on the mesh map. Nothing happened. Cloud you give me some advice?
