### ISSUE TITLE
dynamic local costmap

### ISSUE THREAD

**Issue by roboticsai** [uos/mesh_navigation#21]
Hello while i was studying and experimenting with the mesh_navigatino and move_base_mbf i found that it has no support for real time dynamic obstacles. eg. in ros navigation stack the local costmaps were their which represented the real time obstacles. 
Is their any way in which local costmaps or obstacles can be pepresented in mesh_navigation?

**Comment by spuetz** [comment]
Please note: https://github.com/uos/mesh_navigation/issues/5
