### ISSUE TITLE
I encountered some tough problems when compiling this program , and I don't know how to deal with them.

### ISSUE THREAD

**Issue by ivan1038** [uos/mesh_navigation#3]
here are the errors:
/home/ly/pluto_ws/src/mesh_navigation-master/mbf_mesh_nav/src/mesh_navigation_server.cpp:56:54: error: no matching function for call to ‘mesh_map::MeshMap::MeshMap(tf::TransformListener&)’
   , mesh_ptr_(new mesh_map::MeshMap(*tf_listener_ptr_))
/home/ly/pluto_ws/src/mesh_navigation-master/mbf_mesh_nav/src/mesh_navigation_server.cpp:175:68: error: no matching function for call to ‘mbf_mesh_core::MeshController::initialize(const string&, const TFPtr&, mbf_mesh_nav::MeshNavigationServer::MeshPtr&)’
/home/ly/pluto_ws/src/mesh_navigation-master/mbf_mesh_nav/src/mesh_navigation_server.cpp:219:57: error: no matching function for call to ‘mbf_mesh_core::MeshRecovery::initialize(const string&, const TFPtr&, mbf_mesh_nav::MeshNavigationServer::MeshPtr&)’
   behavior->initialize(name, tf_listener_ptr_, mesh_ptr_);

**Comment by spuetz** [comment]
Are you using kinetic?

**Comment by ivan1038** [comment]
yes，I use ubuntu 16.04 and ros-kinetic. Is the ros-melodic necessary?

**Comment by spuetz** [comment]
yes.
