### ISSUE TITLE
Bad tf tree

### ISSUE THREAD

**Issue by mamoru1126** [uos/mesh_navigation#4]
@spuetz 
I wanted to  run mesh navigation in simulation.
So, According to the tutorial, I used following command.

roslaunch pluto_gazebo pluto_botanical_garden.launch
roslaunch pluto_navigation botanical_garden_osnabrueck.launch

But, I can't run mesh navigation.
I checked my tf tree. Then I noticed that tf between map and odom doesn't exist and Strange tf tree exists.
In general, tf tree of ros navigation is " map ==> odom ==> base_footprint "
Please tell me the solution to this problem

[frames.pdf](https://github.com/uos/mesh_navigation/files/5352713/frames.pdf)

**Comment by spuetz** [comment]
The transformation `map` -> `base_footprint` is published from Gazebo. If you have odomerty in between just use your own config. Btw. mesh navigation is still under construction / development. Cheers.

**Comment by mamoru1126** [comment]
@spuetz 
Thanks for your reply.
 if you don't mind, Please show me your tf _frames and rqt_graph when you run mesh navigation using pluto in simulation.
 I want to use them as a reference.

**Comment by mamoru1126** [comment]
I may have solved this problem. I set value of  enable_odom_tf to false and add   <remap from="tf" to="gazebo_tf"/>  to pluto_gazebo.launch.

Before (pluto_gazeo.launch)
`<node name="gazebo" pkg="gazebo_ros" type="$(arg script_type)" respawn="$(arg respawn_gazebo)" output="screen"
        args="$(arg command_arg1) $(arg command_arg2) $(arg command_arg3) -e $(arg physics) $(arg extra_gazebo_args) $(arg world_name)">
    <remap from="/pluto_velocity_controller/cmd_vel" to="/cmd_vel"/>
    <param name="/pluto_velocity_controller/enable_odom_tf" value="true"/>`

After (pluto_gazeo.launch)
`<node name="gazebo" pkg="gazebo_ros" type="$(arg script_type)" respawn="$(arg respawn_gazebo)" output="screen"
        args="$(arg command_arg1) $(arg command_arg2) $(arg command_arg3) -e $(arg physics) $(arg extra_gazebo_args) $(arg world_name)">
    <remap from="/pluto_velocity_controller/cmd_vel" to="/cmd_vel"/>
    <param name="/pluto_velocity_controller/enable_odom_tf" value="false"/>
    <remap from="tf" to="gazebo_tf"/> `

[After_frames.pdf](https://github.com/uos/mesh_navigation/files/5363852/After_frames.pdf)
