### ISSUE TITLE
opencv2 features 2d not found

### ISSUE THREAD

**Issue by roboticsai** [uos/mesh_navigation#6]
When i'm trying to build this repo with catkin make command. i'm getting below error message:
```
/usr/local/include/lvr2/algorithm/Texturizer.hpp:53:10: fatal error: opencv2/features2d.hpp: No such file or directory
   53 | #include <opencv2/features2d.hpp>
```
I have installed the opencv library with command:
sudo apt-get install libopencv-dev
My plat form is ubuntu 20.04, ros noetic.
I've successfully installed the lvr2 library as described in [this](https://github.com/uos/lvr2) page. 
and the mesh_tools ros package successfully from source.

**Comment by mklpiening** [comment]
Hi, this bug should now be fixed on the latest master.
Thanks for your feedback.
