### ISSUE TITLE
Unable to locate package ros-melodic-mesh-navigation

### ISSUE THREAD

**Issue by fabioruetz** [uos/mesh_navigation#7]
Hi,

when trying to install your package trough " sudo apt install ros-melodic-mesh-navigation" it is unable to find the pack. Is is not released yet?

Cheers

**Comment by mklpiening** [comment]
Hi,
we are currently working on releasing this package in the ros repositories. 
For now, you need to build it from source.

**Comment by spuetz** [comment]
See http://repositories.ros.org/status_page/melodic_default.html
