### ISSUE TITLE
How to run mesh navigation?

### ISSUE THREAD

**Issue by daoran** [uos/mesh_navigation#9]
Thank you for your awesome work.

Could you please provide a tutorial on how to set up this whole system, I cannot get the simulation running like demos.

![demo](https://user-images.githubusercontent.com/10558268/103255572-c310ae00-49c4-11eb-833e-527b9ec6c42d.gif)

**Comment by spuetz** [comment]
We are currently writing a detailed documentation about how to use it. But the best you can do now is to have a look into the `pluto_robot` repo: https://github.com/uos/pluto_robot

**Comment by daoran** [comment]
Thank you for your help, looking forward for your documentation.
